In [2]:
import numpy as np

In [3]:
#index em um array de 1 dimensão
arr = np.array([2, 4, 6, 8])
arr[2]

6

In [4]:
#index em um array de 2 dimensões
arr0 = np.array([4, 5, 6, 7])
arr1 = np.array([3, 9, 2, 1])
arr2 = np.array([arr0, arr1])
print(arr2)
print(arr2[1, 1]) #buscará o elemento 1 no array 1
print(arr2[:, 1]) #buscará todos os elementos 1 do na coluna 1 dos arrays

[[4 5 6 7]
 [3 9 2 1]]
9
[5 9]


<b>Ordenação de um array</b> </p> Axis 0 = Colunas ↑ </p> Axis 1 = Linhas →

In [5]:
np.sort(arr2, axis = 0)

array([[3, 5, 2, 1],
       [4, 9, 6, 7]])

In [6]:
np.sort(arr2, axis = 1)

array([[4, 5, 6, 7],
       [1, 2, 3, 9]])

In [7]:
bingo = np.array([[7, 18, 29, 22],
                [25, 15, 14, 13],
                [10, 26,  4, 26],
                [6, 20,  8, 3]])
bingo

array([[ 7, 18, 29, 22],
       [25, 15, 14, 13],
       [10, 26,  4, 26],
       [ 6, 20,  8,  3]])

In [8]:
#Pegar a segunda coluna, e transformá-la em 1 coluna com 4 linhas
bingo[:, 1].reshape((4,1))

array([[18],
       [15],
       [26],
       [20]])

In [9]:
#Sort do eixo vertical, axis 1
np.sort(bingo) 

array([[ 7, 18, 22, 29],
       [13, 14, 15, 25],
       [ 4, 10, 26, 26],
       [ 3,  6,  8, 20]])

In [10]:
#Sort do eixo horizontal, axis 0
np.sort(bingo, axis = 0) 

array([[ 6, 15,  4,  3],
       [ 7, 18,  8, 13],
       [10, 20, 14, 22],
       [25, 26, 29, 26]])

Indexação sofisticada (fancy indexing) e máscara (mask) em array 2D.

In [11]:
arr2 = np.array([arr0, arr1])
arr2

array([[4, 5, 6, 7],
       [3, 9, 2, 1]])

In [12]:
#Qual dos valores são divisídeis por dois?
arr2[:,] % 2 == 0

array([[ True, False,  True, False],
       [False, False,  True, False]])

<b>Boolean Mask:</b> Retorna um array de verdadeiros e falsos. </p> <b>Fancy indexing:</b> Retorna os valores do array quando passado a máscara. </p><b>np.where():</b> Retorna um array de índices, criando uma matriz com base em os elementos correspondentes a condição.

In [13]:
arr1

array([3, 9, 2, 1])

In [14]:
mask = arr1 % 2 == 0
print(mask)
arr1[mask] #Retornará somente o valor correspondente a verificação

[False False  True False]


array([2])

In [15]:
arr2

array([[4, 5, 6, 7],
       [3, 9, 2, 1]])

In [16]:
np.where(arr2[:, ] % 2 == 0)
#primeiro array localiza as linhas, segundo localiza as colunas
#output - linha 0 coluna 0, linha 0 coluna 2, linha 1 coluna 2

(array([0, 0, 1], dtype=int64), array([0, 2, 2], dtype=int64))

Buscar com where e substituir

In [17]:
np.where(arr2 % 2 == 0, "", arr2)
#ao colocar o nome do array, irá ficar o valor normal
#pela hierarquia de conversão, o array foi convertido para string

array([['', '5', '', '7'],
       ['3', '9', '', '1']], dtype='<U11')

<b>Adicionando e removendo dados</b> </p>Concatenando linhas </p>Concatenando Colunas

In [21]:
arr4 = np.random.randint(10, size = (3, 2))
arr4

array([[2, 0],
       [7, 7],
       [6, 1]])

In [20]:
arr5 = np.array([["Luana", "Murilo"]])
arr5

array([['Luana', 'Murilo']], dtype='<U6')

In [23]:
np.concatenate((arr4, arr5))
#String será o tipo dominante

array([['2', '0'],
       ['7', '7'],
       ['6', '1'],
       ['Luana', 'Murilo']], dtype='<U11')

In [25]:
arr6 = np.array([["Uva", "Abacaxi", "Laranja"]]).reshape((3, 1)) 
#Tranformar num array de 3 linhas com 1 coluna
arr6

array([['Uva'],
       ['Abacaxi'],
       ['Laranja']], dtype='<U7')

In [26]:
np.concatenate((arr4, arr6), axis=1)

array([['2', '0', 'Uva'],
       ['7', '7', 'Abacaxi'],
       ['6', '1', 'Laranja']], dtype='<U11')

Deletando com np.delete()

In [27]:
np.delete(arr6, 2, axis = 0)
#Irá deletar a linha 2 pelo axis 0

array([['Uva'],
       ['Abacaxi']], dtype='<U7')

In [32]:
np.delete(arr4, 1, axis = 1)
#Irá deletar a coluna 1 pelo axis 0

array([[2],
       [7],
       [6]])

<b>Cálculos com Arrays</b> </p> Métodos de agregração de dados: .sum(), .min(), .max(), .mean(), .cumsum()

In [34]:
arr7 = np.random.randint(10, size = (10, 4))
arr7

array([[7, 8, 2, 3],
       [2, 7, 8, 3],
       [2, 9, 3, 9],
       [3, 0, 8, 6],
       [3, 8, 1, 3],
       [4, 1, 4, 4],
       [3, 9, 5, 4],
       [3, 8, 1, 0],
       [0, 6, 0, 6],
       [3, 1, 3, 6]])

In [35]:
arr7.sum()

166

In [36]:
arr7.sum(axis = 0) #soma as colunas

array([30, 57, 35, 44])

In [37]:
arr7.sum(axis = 1) #soma as linhas

array([20, 20, 23, 17, 15, 13, 21, 12, 12, 13])

In [38]:
arr7.min()

0

In [39]:
arr7.max()

9

In [41]:
arr7.max(axis=0) #máximo de cada coluna

array([7, 9, 8, 9])

In [42]:
arr7.mean()

4.15

In [43]:
arr7.mean(axis=0)

array([3. , 5.7, 3.5, 4.4])

Keedims - Manter as mesmas dimensões

In [44]:
9arr7.mean(axis=0, keepdims=True) #Mantem a dimensão

array([[3. , 5.7, 3.5, 4.4]])

Soma culumativa - cumsum

In [45]:
arr7.cumsum(axis=0) #por colunas

array([[ 7,  8,  2,  3],
       [ 9, 15, 10,  6],
       [11, 24, 13, 15],
       [14, 24, 21, 21],
       [17, 32, 22, 24],
       [21, 33, 26, 28],
       [24, 42, 31, 32],
       [27, 50, 32, 32],
       [27, 56, 32, 38],
       [30, 57, 35, 44]])

<b>Operações com Vetorização</b> </p> Ao realizar a soma de elementos em um array utilizando o Numpy, a operação não ocorre de forma individual para cada elemento, em vez disso, ela é realizada de maneira simultânea para todos os elementos do array.

In [47]:
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])

arr1_2d + arr2_2d
#Soma cada elemento do primeiro array com o segundo elemento do segundo array

array([[ 6,  8],
       [10, 12]])

In [48]:
arr1_2d * arr2_2d
#Multiplica cada elemento do primeiro array com o segundo elemento do segundo array

array([[ 5, 12],
       [21, 32]])

In [50]:
arr1_2d  > 3
#Retorna valores booleanos

array([[False, False],
       [False,  True]])

<b>Np.vectorize:</b> Transforma funções Python regulares em funções vetorizadas. Funciona como for, pois percorre os elementos em forma de vetores.

In [68]:
array = np.array([["luana", "lua", "lulu", "moonana", "lubtsuki"]])
len(array) > 5

False

In [69]:
vetor = np.vectorize(len) #vetorizar os valores totais dos elementos, contagem de cada letra
vetor(array) > 5

array([[False, False, False,  True,  True]])

In [71]:
def operacao(x):
    return x**2 + 3*x + 1

vetor_funcao = np.vectorize(operacao) #transforma a função num vetor
array = np.array([1, 2, 3, 4, 5])

resultado = vetor_funcao(array)
resultado

array([ 5, 11, 19, 29, 41])

<b>Broadcasting:</b> Capacidade do NumPy de lidar com operações entre arrays de diferentes formas e tamanhos durante operações artiméticas. Mesmo quando as dimensões entre arrays não forem as mesmas.