In [1]:
import numpy as np

In [2]:
#index em um array de 1 dimensão
arr = np.array([2, 4, 6, 8])
arr[2]

6

In [3]:
#index em um array de 2 dimensões
arr0 = np.array([4, 5, 6, 7])
arr1 = np.array([3, 9, 2, 1])
arr2 = np.array([arr0, arr1])
print(arr2)
print(arr2[1, 1]) #buscará o elemento 1 no array 1
print(arr2[:, 1]) #buscará todos os elementos 1 do na coluna 1 dos arrays

[[4 5 6 7]
 [3 9 2 1]]
9
[5 9]


<b>Ordenação de um array</b> </p> Axis 0 = Colunas ↑ </p> Axis 1 = Linhas →

In [4]:
np.sort(arr2, axis = 0)

array([[3, 5, 2, 1],
       [4, 9, 6, 7]])

In [5]:
np.sort(arr2, axis = 1)

array([[4, 5, 6, 7],
       [1, 2, 3, 9]])

In [6]:
bingo = np.array([[7, 18, 29, 22],
                [25, 15, 14, 13],
                [10, 26,  4, 26],
                [6, 20,  8, 3]])
bingo

array([[ 7, 18, 29, 22],
       [25, 15, 14, 13],
       [10, 26,  4, 26],
       [ 6, 20,  8,  3]])

In [7]:
#Pegar a segunda coluna, e transformá-la em 1 coluna com 4 linhas
bingo[:, 1].reshape((4,1))

array([[18],
       [15],
       [26],
       [20]])

In [8]:
#Sort do eixo vertical, axis 1
np.sort(bingo) 

array([[ 7, 18, 22, 29],
       [13, 14, 15, 25],
       [ 4, 10, 26, 26],
       [ 3,  6,  8, 20]])

In [9]:
#Sort do eixo horizontal, axis 0
np.sort(bingo, axis = 0) 

array([[ 6, 15,  4,  3],
       [ 7, 18,  8, 13],
       [10, 20, 14, 22],
       [25, 26, 29, 26]])

Indexação sofisticada (fancy indexing) e máscara (mask) em array 2D.

In [10]:
arr2 = np.array([arr0, arr1])
arr2

array([[4, 5, 6, 7],
       [3, 9, 2, 1]])

In [11]:
#Qual dos valores são divisídeis por dois?
arr2[:,] % 2 == 0

array([[ True, False,  True, False],
       [False, False,  True, False]])

<b>Boolean Mask:</b> Retorna um array de verdadeiros e falsos. </p> <b>Fancy indexing:</b> Retorna os valores do array quando passado a máscara. </p><b>np.where():</b> Retorna um array de índices, criando uma matriz com base em os elementos correspondentes a condição.

In [12]:
arr1

array([3, 9, 2, 1])

In [13]:
mask = arr1 % 2 == 0
print(mask)
arr1[mask] #Retornará somente o valor correspondente a verificação

[False False  True False]


array([2])

In [14]:
arr2

array([[4, 5, 6, 7],
       [3, 9, 2, 1]])

In [15]:
np.where(arr2[:, ] % 2 == 0)
#primeiro array localiza as linhas, segundo localiza as colunas
#output - linha 0 coluna 0, linha 0 coluna 2, linha 1 coluna 2

(array([0, 0, 1], dtype=int64), array([0, 2, 2], dtype=int64))

Buscar com where e substituir

In [18]:
np.where(arr2 % 2 == 0, "", arr2)
#ao colocar o nome do array, irá ficar o valor normal
#pela hierarquia de conversão, o array foi convertido para string

array([['', '5', '', '7'],
       ['3', '9', '', '1']], dtype='<U11')

Adicionando e removendo dados - Numpy Parte 6