In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Transformando a lista num objeto

In [3]:
arr1 = np.array(l)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#recebe uma tupla que delimita as linhas e colunas, todos os elementos do objeto vão ser 0
np.zeros((2, 2))


array([[0., 0.],
       [0., 0.]])

In [5]:
list(range(0, 3)) #transforma um objeto que vai do 0 ao 3 em uma lista

[0, 1, 2]

In [6]:
#cria um objeto com os índices por range
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#recebe uma tubla, cria objeto com valores randomicos
np.random.random((4, 4)) 

array([[0.5376452 , 0.07323903, 0.54696354, 0.26791065],
       [0.17351549, 0.38850488, 0.52931446, 0.62286351],
       [0.11856556, 0.20807048, 0.14559622, 0.58488993],
       [0.08522287, 0.62823199, 0.11836749, 0.79593834]])

<b>Arrays 3D</b></p>São formatados por três dimensões de vetores.

In [8]:
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])
arr3_2d = np.array([[9, 10], [11, 12]])

arr3_3d = np.array([arr1_2d, arr2_2d, arr3_2d])
arr3_3d
                   

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

<b>Dimensões do array</b> (atributos e métodos) </p> Atributo: .shape [descreve como o array é] </p> Método: .flatten() [achatar o array] ou .reshape() [converte as dimensões]

In [9]:
arr4 = np.array([arr3_3d, arr3_3d])
arr4 #transformar o array de 3 dimensões em 4 dimensões

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]],


       [[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]])

In [10]:
arr4.flatten() #Conversão para array de 1 dimensão

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12])

In [11]:
arz = np.zeros((3, 4, 2))
arz
#array com 3 dimensões, 4 linhas e 2 colunas

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
arz.shape

(3, 4, 2)

In [13]:
arz.flatten()
#irá achar o array para transformar o shape em uma única linha

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

<b>Tipos de objetos Numpy</b> </p> np.int64 | np.int32 | np.float64 | np.float32

In [14]:
np.array([2.14, 6.25, 160.87, 8.4]).dtype

dtype('float64')

In [15]:
np.array([2, 6, 160, 8]).dtype

dtype('int32')

In [16]:
np.array(["Hello", "Coder", "Girls"]).dtype

dtype('<U5')

<b>Conversão e coerção</b>

In [17]:
arr_float = np.array([2.14, 6.25, 160.87]).dtype
print(arr_float) #não convertido
arr_float32 = np.array([2.14, 6.25, 160.87], dtype=np.float32)
print(arr_float32)

float64
[  2.14   6.25 160.87]


In [18]:
arr_vf = np.array([[True, False], [True, True]], dtype=np.bool8)
arr_vf.astype(np.int32) #Conversão do tipo booleano para int

C:\Users\Lua.LUADESKTOP\AppData\Local\Temp\ipykernel_12528\1927162249.py:1: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  arr_vf = np.array([[True, False], [True, True]], dtype=np.bool8)


array([[1, 0],
       [1, 1]])

<b>Hierarquia de coerção:</b> Irá obdecer uma ordem de conversão de elementos conforme estiverem presentes num array. </p> 1.Sring | 2.Float | 3.Int

In [19]:
np.array(["pedra", False , 42, 42.42])

array(['pedra', 'False', '42', '42.42'], dtype='<U32')

In [20]:
np.array([0, 10]).dtype

dtype('int32')

In [21]:
np.array([0, 10, 1.]).dtype
#Se tiver um elemento float na lista, irá converter

dtype('float64')

In [22]:
np.array([True, False]).dtype

dtype('bool')

In [23]:
np.array([True, False, 12]).dtype
#Se tiver um elemento inteiro na lista, irá converter

dtype('int32')