<b>Exercícios - Numpy - WoMakersCode - Data Analytics </b> 
 | Aluna - Luana Lorhanni

<h2> Introdutórios

In [2]:
import numpy as np

<b>1.</b> Crie um array com 4 linhas e 3 colunas com valores aleatórios.

In [3]:
np.random.random((4,3))

array([[0.89129275, 0.79962442, 0.28393644],
       [0.63162917, 0.13094397, 0.6332394 ],
       [0.18571941, 0.49909221, 0.72477171],
       [0.43412576, 0.19620892, 0.13780592]])

<b>2.</b> Crie um array com 5 colunas e 10 linhas inicializados com zeros.

In [4]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<b>3.</b> Crie um array com valores inteiros, 3 linhas e 5 colunas com valores aleatórios.

In [5]:
#10 - limite inferior, 30 - limite superior
#size - linhas e colunas
np.random.randint(10, 30, size = (3,5))

array([[15, 10, 28, 20, 12],
       [25, 22, 13, 18, 12],
       [18, 12, 18, 14, 16]])

<b>4.</b> Crie um array que vá de 0 e 90 pulando de 4 em 4.

In [6]:
a90 = np.random.randint(1, 90, size = (4,4))
a90

array([[34, 88, 27, 20],
       [17, 73,  7, 29],
       [ 5, 62, 24,  2],
       [29, 51, 41, 81]])

<b>5.</b> Reduza o array (5, 7) para apenas uma dimensão.

In [7]:
a57 = np.random.random((5, 7))
a57 = a57.flatten()
a57

array([1.35741235e-01, 2.47341052e-01, 5.57702561e-02, 5.09563924e-01,
       6.96078083e-01, 7.58238317e-01, 9.13686472e-01, 7.14960749e-01,
       3.05606354e-01, 4.24835392e-01, 2.37846444e-01, 7.91918859e-01,
       6.75553372e-01, 2.85061640e-01, 8.12445399e-01, 8.77723611e-02,
       7.37043150e-01, 8.63622193e-01, 3.12433272e-01, 4.87020541e-01,
       1.67202847e-01, 2.88945581e-01, 8.88864456e-01, 6.84456394e-04,
       7.38153598e-01, 5.96980593e-01, 6.49860164e-01, 9.45485272e-01,
       7.35451893e-01, 6.49117311e-01, 8.81777947e-01, 6.17705085e-01,
       1.41964355e-01, 6.51565882e-01, 1.63145671e-01])

<b>6.</b> Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. os números das suas cartelas variam entre 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números (4,3). Crie um array que representa esse jogo.


In [8]:
bingo = np.random.randint(1, 31, size = (10, 4, 3))
bingo #array com 3 dimensões, com 10 arrays dentro dele formatados em 4 linhas e 3 colunas

array([[[ 6, 22,  7],
        [14, 14, 19],
        [ 6, 29, 18],
        [29, 16, 17]],

       [[21, 16, 10],
        [ 1,  1,  1],
        [23, 27,  7],
        [10, 23, 16]],

       [[27, 24, 28],
        [27, 10, 11],
        [27,  2, 17],
        [21,  2, 30]],

       [[ 7, 22,  5],
        [ 4, 17, 30],
        [21, 17, 25],
        [ 8,  4,  8]],

       [[ 3, 29,  7],
        [23,  7, 18],
        [26, 15, 24],
        [ 9, 20, 11]],

       [[30, 22,  2],
        [ 9, 10, 13],
        [23, 21,  5],
        [13, 25, 24]],

       [[14, 18, 21],
        [15, 15, 16],
        [15, 22, 30],
        [27,  7, 29]],

       [[11, 24, 26],
        [ 6, 26, 25],
        [ 3, 17, 29],
        [10, 20, 25]],

       [[ 3,  2,  2],
        [13, 28,  4],
        [ 9,  1, 28],
        [ 8,  3, 24]],

       [[16,  9,  1],
        [ 7, 21,  7],
        [23,  7, 23],
        [18,  9, 16]]])

<b>7.</b> Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.

In [9]:
#5 - quantidade de arrays
bingo.reshape((5, 4, 6))

array([[[ 6, 22,  7, 14, 14, 19],
        [ 6, 29, 18, 29, 16, 17],
        [21, 16, 10,  1,  1,  1],
        [23, 27,  7, 10, 23, 16]],

       [[27, 24, 28, 27, 10, 11],
        [27,  2, 17, 21,  2, 30],
        [ 7, 22,  5,  4, 17, 30],
        [21, 17, 25,  8,  4,  8]],

       [[ 3, 29,  7, 23,  7, 18],
        [26, 15, 24,  9, 20, 11],
        [30, 22,  2,  9, 10, 13],
        [23, 21,  5, 13, 25, 24]],

       [[14, 18, 21, 15, 15, 16],
        [15, 22, 30, 27,  7, 29],
        [11, 24, 26,  6, 26, 25],
        [ 3, 17, 29, 10, 20, 25]],

       [[ 3,  2,  2, 13, 28,  4],
        [ 9,  1, 28,  8,  3, 24],
        [16,  9,  1,  7, 21,  7],
        [23,  7, 23, 18,  9, 16]]])

<h2>Manipulando Arrays

<b>8.</b> Explorando Ecossistemas:
</p>Como bióloga marinha, me encontrei em uma expedição nas
profundezas do Oceano Pacífico, onde estávamos estudando a
biodiversidade e a saúde dos recifes de coral. O catálogo abaixo
demonstra dados das espécies encontradas, considere a seguinte
ordem de colunas: <b>ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie</b>

In [10]:
especies = np.array([[747, 89, 33, 5],
                    [623, 123, 32, 13],
                    [501, 22, 49, 2],
                    [116, 101, 42, 10],
                    [297, 56, 69, 22],
                    [613, 64, 27, 7],
                    [295, 84, 29, 14],
                    [692, 105, 72, 16],
                    [229, 103, 35, 5],
                    [374, 124, 70, 1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

<b>a)</b> Selecione a segunda coluna com a quantidade de espécies
encontradas e adicione em um array as <b>qtd_especies.</b>

In [11]:
qtd_especies =  especies[:, 1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

<b>b)</b> De <b>qtd_especies.</b> selecione apenas as primeiras 3 quantidades e print.

In [12]:
qtd_especies[:3]

array([ 89, 123,  22])

<b>c)</b> Print as 5 últimas quantidades de espécies.

In [13]:
print(especies.shape) #Sabendo que temos  10 linhas com 4 colunas
qtd_especies[-5:] #Selecionar os ultimas 5

(10, 4)


array([ 64,  84, 105, 103, 124])

<b>d)</b> Crie um array que contenha apenas os tamanhos das espécies e
ordene por ordem crescente.

In [14]:
#Vai fazer a ordenação da coluna 3, na ordem invertida
tmh_especies = np.sort(especies[:, 3])[::-1]
tmh_especies

array([22, 16, 14, 13, 10,  7,  5,  5,  2,  1])

<b>e)</b> Usando um index boolean crie um array que contém os dados da
maior espécie encontrada (considerando o seu tamanho), esse
valor corresponde ao valor 22.

In [54]:
np.where(especies[:,3] == 22) #Retorna que na linha 4 está os dados do tamanho 22
tmh_22 = especies[4]
tmh_22

array([297,  56,  69,  22])

<b>f)</b> Usando fency index faça um array que contém apenas dados da
espécie com ID 297.

In [42]:
#Selecionará de todos os elementos a linha que contem 297
id297 = especies[especies[:, 0] == 297]
print(id297)

[[297  56  69  22]]


<b>g)</b> Usando <b>np.where()</b> faça um array com a linha com dados
correspondentes a espécie com 105 representantes
encontrados.

In [45]:
np.where(especies[:, 1] == 105)
especies[7]

array([692, 105,  72,  16])

<b>h)</b> Considere a profundeza em que o espécie foi encontrada
substitua valores maiores que 60 com "Profundo”

In [23]:
profundeza = especies[:,2]
np.where(profundeza > 60, "Profundo", profundeza)
#np.where()

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')

<b>i)</b> Adicione mais 2 espécies ao array: </p>[[204, 10, 40, 12], </p>[392, 11, 81, 11]]

In [ ]:
especies

<b>j)</b> Adicione mais uma coluna na no array original agora com o
número de espécies encontradas com que indica se o animal
enxerga ou não: </p>[0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0].

<h2> Cáculo com Array

<b>1.</b> Considerando o array abaixo, responda:

In [ ]:
acidentes = np.array([[1, 3, 2],
    [0, 1, 0],
    [2, 1, 4],
    [0, 0, 0],
    [1, 1, 0]])

<b>a)</b> O cliente que teve acidente abaixo da média nos últimos 2 anos, ganhará um desconto no seu seguro. Identifique-os.

<b>b)</b> Qual cliente teve pelo menos 2 anos sem cometer acidentes?

<b>c)</b> Uma professora quer que seus alunos apliquem a função (3x + 2y + x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e
pede que seja feita essa operação.

<b>d)</b> A mesma professora percebeu que houve um erro em todas as provas dos estudantes e esqueceu de anotar a nota de trabalhos
apresentados durante o semestre. Já que foi feito em grupo ela vai
adicionar a mesma nota para todos os estudantes. No array cada
estudante representa uma linha e cada coluna uma prova. Adicione
para cada prova de cada estudante os valores: 1, 2, 1.