<b>Exercícios - Numpy - WoMakersCode - Data Analytics </b> 
 | Aluna - Luana Lorhanni

<h2> Introdutórios

In [2]:
import numpy as np

<b>1.</b> Crie um array com 4 linhas e 3 colunas com valores aleatórios.

In [3]:
np.random.random((4,3))

array([[0.64156208, 0.86999157, 0.79277245],
       [0.72290723, 0.0410744 , 0.32139267],
       [0.55570429, 0.64934232, 0.9167633 ],
       [0.07680167, 0.9712079 , 0.42384059]])

<b>2.</b> Crie um array com 5 colunas e 10 linhas inicializados com zeros.

In [4]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<b>3.</b> Crie um array com valores inteiros, 3 linhas e 5 colunas com valores aleatórios.

In [5]:
#10 - limite inferior, 30 - limite superior
#size - linhas e colunas
np.random.randint(10, 30, size = (3,5))

array([[25, 29, 25, 22, 26],
       [17, 18, 29, 16, 15],
       [13, 26, 14, 27, 10]])

<b>4.</b> Crie um array que vá de 0 e 90 pulando de 4 em 4.

In [6]:
a90 = np.random.randint(1, 90, size = (4,4))
a90

array([[18, 67, 71,  1],
       [31, 81, 44, 65],
       [74, 78, 82,  4],
       [37, 87, 85, 65]])

<b>5.</b> Reduza o array (5, 7) para apenas uma dimensão.

In [7]:
a57 = np.random.random((5, 7))
a57 = a57.flatten()
a57

array([0.45156798, 0.01554294, 0.7441342 , 0.73364507, 0.35086906,
       0.03702907, 0.64949563, 0.16362322, 0.99255082, 0.9397939 ,
       0.53226188, 0.18786659, 0.29283255, 0.10435865, 0.09440146,
       0.12569842, 0.10913792, 0.10806558, 0.02897089, 0.40333563,
       0.93050498, 0.30546051, 0.58709287, 0.56051712, 0.87653021,
       0.31525474, 0.99676894, 0.98435592, 0.43497138, 0.69495451,
       0.4143805 , 0.36831997, 0.76725856, 0.98124233, 0.36092529])

<b>6.</b> Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. os números das suas cartelas variam entre 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números (4,3). Crie um array que representa esse jogo.


In [8]:
bingo = np.random.randint(1, 31, size = (10, 4, 3))
bingo #array com 3 dimensões, com 10 arrays dentro dele formatados em 4 linhas e 3 colunas

array([[[30, 12, 14],
        [23, 16, 25],
        [30, 23, 25],
        [12, 16, 12]],

       [[12, 30, 30],
        [ 8, 21, 11],
        [ 7, 30, 23],
        [28,  2, 29]],

       [[16, 21, 12],
        [29,  4,  5],
        [27, 19,  8],
        [10,  4, 10]],

       [[ 3, 13, 24],
        [27, 27,  4],
        [ 5, 28, 12],
        [ 5, 11, 28]],

       [[10, 30, 11],
        [28,  9, 23],
        [19, 11, 11],
        [27, 29,  9]],

       [[23, 25, 28],
        [12, 22,  5],
        [29, 17, 23],
        [26, 15,  8]],

       [[11, 15,  2],
        [19,  5,  6],
        [11, 25, 26],
        [24,  8,  8]],

       [[29,  1, 18],
        [11, 10, 26],
        [ 9, 18, 18],
        [30, 10, 20]],

       [[21, 24, 10],
        [10, 15, 30],
        [24, 10, 22],
        [ 9, 29, 20]],

       [[30, 13, 25],
        [20, 14,  1],
        [21, 22, 30],
        [22,  3, 16]]])

<b>7.</b> Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.

In [9]:
#5 - quantidade de arrays
bingo.reshape((5, 4, 6))

array([[[30, 12, 14, 23, 16, 25],
        [30, 23, 25, 12, 16, 12],
        [12, 30, 30,  8, 21, 11],
        [ 7, 30, 23, 28,  2, 29]],

       [[16, 21, 12, 29,  4,  5],
        [27, 19,  8, 10,  4, 10],
        [ 3, 13, 24, 27, 27,  4],
        [ 5, 28, 12,  5, 11, 28]],

       [[10, 30, 11, 28,  9, 23],
        [19, 11, 11, 27, 29,  9],
        [23, 25, 28, 12, 22,  5],
        [29, 17, 23, 26, 15,  8]],

       [[11, 15,  2, 19,  5,  6],
        [11, 25, 26, 24,  8,  8],
        [29,  1, 18, 11, 10, 26],
        [ 9, 18, 18, 30, 10, 20]],

       [[21, 24, 10, 10, 15, 30],
        [24, 10, 22,  9, 29, 20],
        [30, 13, 25, 20, 14,  1],
        [21, 22, 30, 22,  3, 16]]])

<h2>Manipulando Arrays

<b>8.</b> Explorando Ecossistemas:
</p>Como bióloga marinha, me encontrei em uma expedição nas
profundezas do Oceano Pacífico, onde estávamos estudando a
biodiversidade e a saúde dos recifes de coral. O catálogo abaixo
demonstra dados das espécies encontradas, considere a seguinte
ordem de colunas: <b>ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie</b>

In [10]:
especies = np.array([[747, 89, 33, 5],
                    [623, 123, 32, 13],
                    [501, 22, 49, 2],
                    [116, 101, 42, 10],
                    [297, 56, 69, 22],
                    [613, 64, 27, 7],
                    [295, 84, 29, 14],
                    [692, 105, 72, 16],
                    [229, 103, 35, 5],
                    [374, 124, 70, 1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

<b>a)</b> Selecione a segunda coluna com a quantidade de espécies
encontradas e adicione em um array as <b>qtd_especies.</b>

In [11]:
qtd_especies =  especies[:, 1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

<b>b)</b> De <b>qtd_especies.</b> selecione apenas as primeiras 3 quantidades e print.

In [12]:
qtd_especies[:3]

array([ 89, 123,  22])

<b>c)</b> Print as 5 últimas quantidades de espécies.

In [13]:
print(especies.shape) #Sabendo que temos  10 linhas com 4 colunas
qtd_especies[-5:] #Selecionar os ultimas 5

(10, 4)


array([ 64,  84, 105, 103, 124])

<b>d)</b> Crie um array que contenha apenas os tamanhos das espécies e
ordene por ordem crescente.

In [14]:
#Vai fazer a ordenação da coluna 3, na ordem invertida
tmh_especies = np.sort(especies[:, 3])[::-1]
tmh_especies

array([22, 16, 14, 13, 10,  7,  5,  5,  2,  1])

<b>e)</b> Usando um index boolean crie um array que contém os dados da
maior espécie encontrada (considerando o seu tamanho), esse
valor corresponde ao valor 22.

In [15]:
np.where(especies[:,3] == 22) #Retorna que na linha 4 está os dados do tamanho 22
tmh_22 = especies[4]
tmh_22

array([297,  56,  69,  22])

<b>f)</b> Usando fency index faça um array que contém apenas dados da
espécie com ID 297.

In [16]:
#Selecionará de todos os elementos a linha que contem 297
id297 = especies[especies[:, 0] == 297]
print(id297)

[[297  56  69  22]]


<b>g)</b> Usando <b>np.where()</b> faça um array com a linha com dados
correspondentes a espécie com 105 representantes
encontrados.

In [17]:
np.where(especies[:, 1] == 105)
especies[7]

array([692, 105,  72,  16])

<b>h)</b> Considere a profundeza em que o espécie foi encontrada
substitua valores maiores que 60 com "Profundo”

In [18]:
profundeza = especies[:,2]
np.where(profundeza > 60, "Profundo", profundeza)
#np.where()

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')

<b>i)</b> Adicione mais 2 espécies ao array: </p>[[204, 10, 40, 12], </p>[392, 11, 81, 11]]

In [36]:
esp1 = np.array([[204, 10, 40, 12]])
esp2 = np.array([[392, 11, 81, 11]])
novas_especies = np.concatenate((esp1, esp2))
especies = np.concatenate((especies, novas_especies), axis = 0)
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11],
       [204,  10,  40,  12],
       [392,  11,  81,  11],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

<b>j)</b> Adicione mais uma coluna na no array original agora com o
número de espécies encontradas com que indica se o animal
enxerga ou não: </p>[0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0].

In [47]:
enx = np.array([[0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0]]).reshape(16, 1) #transformação para coluna
especies = np.concatenate((especies, enx), axis = 1) #axis de coluna
especies

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1],
       [204,  10,  40,  12,   0],
       [392,  11,  81,  11,   1],
       [204,  10,  40,  12,   0],
       [392,  11,  81,  11,   1],
       [204,  10,  40,  12,   0],
       [392,  11,  81,  11,   0]])

<h2> Cáculo com Array

<b>1.</b> Considerando o array abaixo, responda:

In [20]:
acidentes = np.array([[1, 3, 2],
    [0, 1, 0],
    [2, 1, 4],
    [0, 0, 0],
    [1, 1, 0]])

<b>a)</b> O cliente que teve acidente abaixo da média nos últimos 2 anos, ganhará um desconto no seu seguro. Identifique-os.

In [59]:
media = acidentes.mean()
acidentes > media

array([[False,  True,  True],
       [False, False, False],
       [ True, False,  True],
       [False, False, False],
       [False, False, False]])

<b>b)</b> Qual cliente teve pelo menos 2 anos sem cometer acidentes?

In [61]:
np.where(acidentes[:,2] == 2)
#Retorna a primeira linha

(array([0], dtype=int64),)

<b>c)</b> Uma professora quer que seus alunos apliquem a função (3x + 2y + x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e
pede que seja feita essa operação.

In [52]:
def operacao(x):
    return x**2 + 3*x + 1

vetor_funcao = np.vectorize(operacao) #transforma a função num vetor
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

resultado1 = vetor_funcao(array1)
resultado2 = vetor_funcao(array2)
print(resultado1)
print(resultado2)  

[ 5 11 19 29 41]
[ 55  71  89 109 131]


<b>d)</b> A mesma professora percebeu que houve um erro em todas as provas dos estudantes e esqueceu de anotar a nota de trabalhos
apresentados durante o semestre. Já que foi feito em grupo ela vai
adicionar a mesma nota para todos os estudantes. No array cada
estudante representa uma linha e cada coluna uma prova. Adicione
para cada prova de cada estudante os valores: 1, 2, 1.

In [58]:
provas = np.array([[1, 2, 1]])
alunos = np.array([["aluno 1", "aluno 2", "aluno 3"]])

notas = np.array([provas, alunos])
notas

array([[['1', '2', '1']],

       [['aluno 1', 'aluno 2', 'aluno 3']]], dtype='<U11')